# Created by and for Qt Creator This file was created for editing the project sources only.
# You may attempt to use it for building too, by modifying this file here.

#TARGET = DORB-SLAM2

HEADERS = \
   $$PWD/Examples/ROS/ORB_SLAM2/src/AR/ViewerAR.h \
   $$PWD/include/Converter.h \
   $$PWD/include/Frame.h \
   $$PWD/include/FrameDrawer.h \
   $$PWD/include/Initializer.h \
   $$PWD/include/KeyFrame.h \
   $$PWD/include/KeyFrameDatabase.h \
   $$PWD/include/LocalMapping.h \
   $$PWD/include/LoopClosing.h \
   $$PWD/include/Map.h \
   $$PWD/include/MapDrawer.h \
   $$PWD/include/MapPoint.h \
   $$PWD/include/Optimizer.h \
   $$PWD/include/ORBextractor.h \
   $$PWD/include/ORBmatcher.h \
   $$PWD/include/ORBVocabulary.h \
   $$PWD/include/PnPsolver.h \
   $$PWD/include/Sim3Solver.h \
   $$PWD/include/System.h \
   $$PWD/include/Tracking.h \
   $$PWD/include/Viewer.h \
   $$PWD/Thirdparty/DBoW2/DBoW2/BowVector.h \
   $$PWD/Thirdparty/DBoW2/DBoW2/FClass.h \
   $$PWD/Thirdparty/DBoW2/DBoW2/FeatureVector.h \
   $$PWD/Thirdparty/DBoW2/DBoW2/FORB.h \
   $$PWD/Thirdparty/DBoW2/DBoW2/ScoringObject.h \
   $$PWD/Thirdparty/DBoW2/DBoW2/TemplatedVocabulary.h \
   $$PWD/Thirdparty/DBoW2/DUtils/Random.h \
   $$PWD/Thirdparty/DBoW2/DUtils/Timestamp.h \
   $$PWD/Thirdparty/g2o/g2o/core/base_binary_edge.h \
   $$PWD/Thirdparty/g2o/g2o/core/base_binary_edge.hpp \
   $$PWD/Thirdparty/g2o/g2o/core/base_edge.h \
   $$PWD/Thirdparty/g2o/g2o/core/base_multi_edge.h \
   $$PWD/Thirdparty/g2o/g2o/core/base_multi_edge.hpp \
   $$PWD/Thirdparty/g2o/g2o/core/base_unary_edge.h \
   $$PWD/Thirdparty/g2o/g2o/core/base_unary_edge.hpp \
   $$PWD/Thirdparty/g2o/g2o/core/base_vertex.h \
   $$PWD/Thirdparty/g2o/g2o/core/base_vertex.hpp \
   $$PWD/Thirdparty/g2o/g2o/core/batch_stats.h \
   $$PWD/Thirdparty/g2o/g2o/core/block_solver.h \
   $$PWD/Thirdparty/g2o/g2o/core/block_solver.hpp \
   $$PWD/Thirdparty/g2o/g2o/core/cache.h \
   $$PWD/Thirdparty/g2o/g2o/core/creators.h \
   $$PWD/Thirdparty/g2o/g2o/core/eigen_types.h \
   $$PWD/Thirdparty/g2o/g2o/core/estimate_propagator.h \
   $$PWD/Thirdparty/g2o/g2o/core/factory.h \
   $$PWD/Thirdparty/g2o/g2o/core/hyper_dijkstra.h \
   $$PWD/Thirdparty/g2o/g2o/core/hyper_graph.h \
   $$PWD/Thirdparty/g2o/g2o/core/hyper_graph_action.h \
   $$PWD/Thirdparty/g2o/g2o/core/jacobian_workspace.h \
   $$PWD/Thirdparty/g2o/g2o/core/linear_solver.h \
   $$PWD/Thirdparty/g2o/g2o/core/marginal_covariance_cholesky.h \
   $$PWD/Thirdparty/g2o/g2o/core/matrix_operations.h \
   $$PWD/Thirdparty/g2o/g2o/core/matrix_structure.h \
   $$PWD/Thirdparty/g2o/g2o/core/openmp_mutex.h \
   $$PWD/Thirdparty/g2o/g2o/core/optimizable_graph.h \
   $$PWD/Thirdparty/g2o/g2o/core/optimization_algorithm.h \
   $$PWD/Thirdparty/g2o/g2o/core/optimization_algorithm_dogleg.h \
   $$PWD/Thirdparty/g2o/g2o/core/optimization_algorithm_factory.h \
   $$PWD/Thirdparty/g2o/g2o/core/optimization_algorithm_gauss_newton.h \
   $$PWD/Thirdparty/g2o/g2o/core/optimization_algorithm_levenberg.h \
   $$PWD/Thirdparty/g2o/g2o/core/optimization_algorithm_property.h \
   $$PWD/Thirdparty/g2o/g2o/core/optimization_algorithm_with_hessian.h \
   $$PWD/Thirdparty/g2o/g2o/core/parameter.h \
   $$PWD/Thirdparty/g2o/g2o/core/parameter_container.h \
   $$PWD/Thirdparty/g2o/g2o/core/robust_kernel.h \
   $$PWD/Thirdparty/g2o/g2o/core/robust_kernel_factory.h \
   $$PWD/Thirdparty/g2o/g2o/core/robust_kernel_impl.h \
   $$PWD/Thirdparty/g2o/g2o/core/solver.h \
   $$PWD/Thirdparty/g2o/g2o/core/sparse_block_matrix.h \
   $$PWD/Thirdparty/g2o/g2o/core/sparse_block_matrix.hpp \
   $$PWD/Thirdparty/g2o/g2o/core/sparse_block_matrix_ccs.h \
   $$PWD/Thirdparty/g2o/g2o/core/sparse_block_matrix_diagonal.h \
   $$PWD/Thirdparty/g2o/g2o/core/sparse_optimizer.h \
   $$PWD/Thirdparty/g2o/g2o/solvers/linear_solver_dense.h \
   $$PWD/Thirdparty/g2o/g2o/solvers/linear_solver_eigen.h \
   $$PWD/Thirdparty/g2o/g2o/stuff/color_macros.h \
   $$PWD/Thirdparty/g2o/g2o/stuff/macros.h \
   $$PWD/Thirdparty/g2o/g2o/stuff/misc.h \
   $$PWD/Thirdparty/g2o/g2o/stuff/os_specific.h \
   $$PWD/Thirdparty/g2o/g2o/stuff/property.h \
   $$PWD/Thirdparty/g2o/g2o/stuff/string_tools.h \
   $$PWD/Thirdparty/g2o/g2o/stuff/timeutil.h \
   $$PWD/Thirdparty/g2o/g2o/types/se3_ops.h \
   $$PWD/Thirdparty/g2o/g2o/types/se3_ops.hpp \
   $$PWD/Thirdparty/g2o/g2o/types/se3quat.h \
   $$PWD/Thirdparty/g2o/g2o/types/sim3.h \
   $$PWD/Thirdparty/g2o/g2o/types/types_sba.h \
   $$PWD/Thirdparty/g2o/g2o/types/types_seven_dof_expmap.h \
   $$PWD/Thirdparty/g2o/g2o/types/types_six_dof_expmap.h \
   $$PWD/Thirdparty/g2o/config.h

SOURCES = \
   $$PWD/Examples/Monocular/mono_euroc.cc \
   $$PWD/Examples/Monocular/mono_kitti.cc \
   $$PWD/Examples/Monocular/mono_tum.cc \
   $$PWD/Examples/RGB-D/rgbd_tum.cc \
   $$PWD/Examples/ROS/ORB_SLAM2/src/AR/ros_mono_ar.cc \
   $$PWD/Examples/ROS/ORB_SLAM2/src/AR/ViewerAR.cc \
   $$PWD/Examples/ROS/ORB_SLAM2/src/ros_mono.cc \
   $$PWD/Examples/ROS/ORB_SLAM2/src/ros_rgbd.cc \
   $$PWD/Examples/ROS/ORB_SLAM2/src/ros_stereo.cc \
   $$PWD/Examples/Stereo/stereo_euroc.cc \
   $$PWD/Examples/Stereo/stereo_kitti.cc \
   $$PWD/src/Converter.cc \
   $$PWD/src/Frame.cc \
   $$PWD/src/FrameDrawer.cc \
   $$PWD/src/Initializer.cc \
   $$PWD/src/KeyFrame.cc \
   $$PWD/src/KeyFrameDatabase.cc \
   $$PWD/src/LocalMapping.cc \
   $$PWD/src/LoopClosing.cc \
   $$PWD/src/Map.cc \
   $$PWD/src/MapDrawer.cc \
   $$PWD/src/MapPoint.cc \
   $$PWD/src/Optimizer.cc \
   $$PWD/src/ORBextractor.cc \
   $$PWD/src/ORBmatcher.cc \
   $$PWD/src/PnPsolver.cc \
   $$PWD/src/Sim3Solver.cc \
   $$PWD/src/System.cc \
   $$PWD/src/Tracking.cc \
   $$PWD/src/Viewer.cc \
   $$PWD/Thirdparty/DBoW2/DBoW2/BowVector.cpp \
   $$PWD/Thirdparty/DBoW2/DBoW2/FeatureVector.cpp \
   $$PWD/Thirdparty/DBoW2/DBoW2/FORB.cpp \
   $$PWD/Thirdparty/DBoW2/DBoW2/ScoringObject.cpp \
   $$PWD/Thirdparty/DBoW2/DUtils/Random.cpp \
   $$PWD/Thirdparty/DBoW2/DUtils/Timestamp.cpp \
   $$PWD/Thirdparty/g2o/g2o/core/batch_stats.cpp \
   $$PWD/Thirdparty/g2o/g2o/core/cache.cpp \
   $$PWD/Thirdparty/g2o/g2o/core/estimate_propagator.cpp \
   $$PWD/Thirdparty/g2o/g2o/core/factory.cpp \
   $$PWD/Thirdparty/g2o/g2o/core/hyper_dijkstra.cpp \
   $$PWD/Thirdparty/g2o/g2o/core/hyper_graph.cpp \
   $$PWD/Thirdparty/g2o/g2o/core/hyper_graph_action.cpp \
   $$PWD/Thirdparty/g2o/g2o/core/jacobian_workspace.cpp \
   $$PWD/Thirdparty/g2o/g2o/core/marginal_covariance_cholesky.cpp \
   $$PWD/Thirdparty/g2o/g2o/core/matrix_structure.cpp \
   $$PWD/Thirdparty/g2o/g2o/core/optimizable_graph.cpp \
   $$PWD/Thirdparty/g2o/g2o/core/optimization_algorithm.cpp \
   $$PWD/Thirdparty/g2o/g2o/core/optimization_algorithm_dogleg.cpp \
   $$PWD/Thirdparty/g2o/g2o/core/optimization_algorithm_factory.cpp \
   $$PWD/Thirdparty/g2o/g2o/core/optimization_algorithm_gauss_newton.cpp \
   $$PWD/Thirdparty/g2o/g2o/core/optimization_algorithm_levenberg.cpp \
   $$PWD/Thirdparty/g2o/g2o/core/optimization_algorithm_with_hessian.cpp \
   $$PWD/Thirdparty/g2o/g2o/core/parameter.cpp \
   $$PWD/Thirdparty/g2o/g2o/core/parameter_container.cpp \
   $$PWD/Thirdparty/g2o/g2o/core/robust_kernel.cpp \
   $$PWD/Thirdparty/g2o/g2o/core/robust_kernel_factory.cpp \
   $$PWD/Thirdparty/g2o/g2o/core/robust_kernel_impl.cpp \
   $$PWD/Thirdparty/g2o/g2o/core/solver.cpp \
   $$PWD/Thirdparty/g2o/g2o/core/sparse_block_matrix_test.cpp \
   $$PWD/Thirdparty/g2o/g2o/core/sparse_optimizer.cpp \
   $$PWD/Thirdparty/g2o/g2o/stuff/os_specific.c \
   $$PWD/Thirdparty/g2o/g2o/stuff/property.cpp \
   $$PWD/Thirdparty/g2o/g2o/stuff/string_tools.cpp \
   $$PWD/Thirdparty/g2o/g2o/stuff/timeutil.cpp \
   $$PWD/Thirdparty/g2o/g2o/types/types_sba.cpp \
   $$PWD/Thirdparty/g2o/g2o/types/types_seven_dof_expmap.cpp \
   $$PWD/Thirdparty/g2o/g2o/types/types_six_dof_expmap.cpp

INCLUDEPATH = \
    $$PWD/Examples/ROS/ORB_SLAM2/src/AR \
    $$PWD/include \
    $$PWD/Thirdparty/DBoW2/DBoW2 \
    $$PWD/Thirdparty/DBoW2/DUtils \
    $$PWD/Thirdparty/g2o \
    $$PWD/Thirdparty/g2o/g2o/core \
    $$PWD/Thirdparty/g2o/g2o/solvers \
    $$PWD/Thirdparty/g2o/g2o/stuff \
    $$PWD/Thirdparty/g2o/g2o/types

#DEFINES = 

